version: "3.8"
services:
  fastapi:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8083:8000"
      - "50052:50052"
    networks:
      - app-network
    environment:
      - RAFT_NODE_ID=node3

  nodejs:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8084:8084"
      - "50053:50053"
    networks:
      - app-network
    environment:
      - RAFT_NODE_ID=node4

networks:
  app-network:
    driver: bridge
